<h1>
Unsupervised Machine Learning with
</h1>
<h1>
One-Class (SVMs) Support Vector Machines
</h1>

In [2]:
%matplotlib inline

import numpy as np
import pandas as pd
from sklearn import utils
import matplotlib

data = pd.read_csv('common_sites_aqua_distance.csv', low_memory=False)
print ('Number of rows in initial data set {}'.format(data.size))

# data.set_index('id')

Number of rows in initial data set 12176

1. Extracting the relevant features in our data (which seems to be all of them so far except the id and coordinate fields)
<br>
2. Replace the data with a subset containing only the relevant features (again, which seems to be all of them until further changes)
<br>
3. Next we normalize the data - this leads to better accuracy and reduces the numerical instability in the SVM

In [3]:
list(data)

['Country',
 'Latitude',
 'Longitude',
 'SiteID',
 'Elevation',
 'SiteName',
 'Distance matrix lakes_Distance',
 'Distance matrix rivers_Distance']

In [4]:
# extract features
relevant_features = [
    'Elevation',
    'Distance matrix lakes_Distance',
    'Distance matrix rivers_Distance'
]

# replace data
data = data[relevant_features]

# normalize the data
for feature in relevant_features:
    data[feature] = np.log((data[feature] + 0.1).astype(float))

# print data
data

,Elevation,Distance matrix lakes_Distance,Distance matrix rivers_Distance
0,5.318610,0.649659,0.566866
1,4.821088,1.492799,-0.939658
2,-2.302585,1.360694,0.058422
3,-2.302585,0.644151,0.708386
4,4.852811,-0.299526,-1.425983
5,-2.302585,1.716673,-1.049898
6,5.075799,-0.281390,0.620001
7,-2.302585,0.012866,-1.195684
8,4.821088,1.479244,-0.553765
9,-2.302585,1.525927,-0.251569
10,-2.302585,1.535810,-0.240676
11,5.106551,0.106600,-0.905697
12,4.616110,-0.869052,-0.266499
13,3.404525,1.368397,0.106427
14,3.640214,0.087775,-1.726519
15,1.960095,1.454938,0.035748
16,4.804840,1.519358,-0.704642
17,5.606170,0.048752,-0.803017
18,5.533785,-0.162233,0.267483
19,5.323498,1.393646,-0.892679
20,4.728272,1.368160,-0.715275
21,-2.302585,0.554715,0.161384
22,-2.302585,0.037034,-1.116134
23,-2.302585,0.647567,0.590547
24,-2.302585,-1.216339,-0.998541
25,-2.302585,0.505840,-1.157568
26,4.432007,-1.196668,-0.174698
27,-2.302585,0.398916,-1.498127
28,-2.302585,0.058416,-0.669046
29,-2.302585,0.315037,-2.167689
...,...,...,...
1492,3.740048,1.416216,-0.099516
1493,4.144721,1.348860,0.087346
1494,4.009150,1.342080,0.017747
1495,4.345103,1.450369,-0.392104
1496,-2.302585,1.451355,-0.471603
1497,-2.302585,1.249280,0.320699
1498,4.370713,1.331304,-0.314832
1499,4.710431,1.395945,-0.091514
1500,4.544358,0.280527,-0.705053
1501,5.242276,-0.268058,-0.424795
1502,3.972177,0.282258,-0.688526
1503,-2.302585,-0.135321,-0.629957
1504,-2.302585,0.121820,-2.160282
1505,4.913390,1.386158,-2.168950
1506,4.370713,1.500785,0.059111
1507,2.091864,1.530822,0.007428
1508,-2.302585,0.563449,0.826488
1509,3.261935,-0.647825,0.029392
1510,-2.302585,0.644674,0.708583
1511,4.489759,1.286523,0.120616
1512,-2.302585,-1.271461,-0.921313
1513,-2.302585,1.704052,-0.799185
1514,4.191169,1.562531,0.297990
1515,4.191169,1.563150,0.295681
1516,2.646175,1.531123,0.186849
1517,-2.302585,1.579319,-1.053941
1518,-2.302585,1.706381,-0.803648
1519,-2.302585,1.330901,0.229839
1520,4.175925,1.562798,0.297308
1521,4.062166,1.391049,-1.627894

<h2>Making our Data one-class</h2>
<br>
We're using a one-class SVM, so we need.. a single class
<br>
All the data we have is positive so we have
<br>
class 1 (site)

In [5]:
data['site'] = 1.0
data.head(5)

,Elevation,Distance matrix lakes_Distance,Distance matrix rivers_Distance,site
0,5.318610,0.649659,0.566866,1.0
1,4.821088,1.492799,-0.939658,1.0
2,-2.302585,1.360694,0.058422,1.0
3,-2.302585,0.644151,0.708386,1.0
4,4.852811,-0.299526,-1.425983,1.0

Grab out the site value as the target for training and testing
<br>
Since we're only selecting a single column from the 'data' dataframe, we'll just get a series, not a new data frame

In [6]:
target = data['site']
target

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
5       1.0
6       1.0
7       1.0
8       1.0
9       1.0
10      1.0
11      1.0
12      1.0
13      1.0
14      1.0
15      1.0
16      1.0
17      1.0
18      1.0
19      1.0
20      1.0
21      1.0
22      1.0
23      1.0
24      1.0
25      1.0
26      1.0
27      1.0
28      1.0
29      1.0
       ...
1492    1.0
1493    1.0
1494    1.0
1495    1.0
1496    1.0
1497    1.0
1498    1.0
1499    1.0
1500    1.0
1501    1.0
1502    1.0
1503    1.0
1504    1.0
1505    1.0
1506    1.0
1507    1.0
1508    1.0
1509    1.0
1510    1.0
1511    1.0
1512    1.0
1513    1.0
1514    1.0
1515    1.0
1516    1.0
1517    1.0
1518    1.0
1519    1.0
1520    1.0
1521    1.0
Name: site, Length: 1522, dtype: float64

Find proportion? 
<br>
maybe. skip this for now

We drop site column name from the data frame so we can do unsupervied training with unlabelled data. We've already copied the site column name out into the target series so we can compare against it later

In [8]:
data.drop(['site'], axis=1, inplace=True)
data.head(5)

   Elevation  Distance matrix lakes_Distance  Distance matrix rivers_Distance
0   5.318610                        0.649659                         0.566866
1   4.821088                        1.492799                        -0.939658
2  -2.302585                        1.360694                         0.058422
3  -2.302585                        0.644151                         0.708386
4   4.852811                       -0.299526                        -1.425983

Check the shape for sanity checking

In [9]:
data.shape

(1522, 3)

<h2>
Splitting the Data into Training and Test Sets
</h2>

In [10]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(data, target, train_size=0.8)

train_data.shape

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

(1217, 3)

<strong>nu</strong>     - 'An upper bound on the fraction of training errors and a lower bound of the fraction of support vectors' and must be between 0 and 1. Basically this means the proportion of outliers we expect in our data.
<br>
<strong>kernel</strong> - the kernel type to be used. Setting kernel to something other than linear here will achieve that. The default is rbf (RBF - radial basis function).

<strong>gamma</strong>  - parameter of the RBF kernel type and controls the influence of individual training samples, the effects the 'smoothness' of the model. A low value improves the smoothness and "generalizability" of the model, while a high values reduces it but makes the model "tighter-fitted" to the training data. Some experimentation is often required to find the best value.

In [ ]:
from sklearn import svm

# set nu (which should be proportion of outliers in our data, but we don't exactly know it)
# attributes (nu=0.01, kernel='rbf', gamma=0.00005)
model = svm.OneClassSVM()
model.fit(train_data)

from sklearn import metrics
preds = model.predict(train_data)
targs = train_target

args = (targs, preds)

print("accuracy:  ", metrics.accuracy_score(*args))
print("precision: ", metrics.precision_score(*args))
print("recall:    ", metrics.recall_score(*args))
print("f1:        ", metrics.f1_score(*args))
# print("area under curve (auc): ", metrics.roc_auc_score(*args))

In [11]:
from sklearn import svm

# set nu (which should be proportion of outliers in our data, but we don't exactly know it)
# attributes (nu=0.01, kernel='rbf', gamma=0.00005)
model = svm.OneClassSVM()
model.fit(train_data)

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma='auto', kernel='rbf',
      max_iter=-1, nu=0.5, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

In [13]:
from sklearn import metrics
preds = model.predict(train_data)
targs = train_target

args = (targs, preds)

print("accuracy:  ", metrics.accuracy_score(*args))
print("precision: ", metrics.precision_score(*args))
print("recall:    ", metrics.recall_score(*args))
print("f1:        ", metrics.f1_score(*args))
# print("area under curve (auc): ", metrics.roc_auc_score(*args))

accuracy:   0.49958915365653245
precision:  1.0
recall:     0.49958915365653245
f1:         0.6663013698630137